//Usuario
POST http://localhost:3000/insertar HTTP/1.1
Content-Type: application/json

{
    "nombre": "SETTO",
    "mail": "SETTO@gmail.com",
    "Contraseña":"SETTO",
    "admin": true
}

###
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    
    "Mail": "SETTO@gmail.com",
    "Contraseña":"SETTO"
}

###

GET http://localhost:3000/Selector/benjapiccagli@gmail.com HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkVDSFUxM0BnbWFpbC5jb20iLCJpYXQiOjE3MjczNjI5NjksImV4cCI6MzUyNzM2Mjk2OX0.TPY5Sk8IoeN7tv3dxLcKUMWOGffWU44HDF7qOAKc_sM

### 

DELETE http://localhost:3000/delUsuario/BA@gmail.com HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkVDSFUxM0BnbWFpbC5jb20iLCJpYXQiOjE3MjczNjI5NjksImV4cCI6MzUyNzM2Mjk2OX0.TPY5Sk8IoeN7tv3dxLcKUMWOGffWU44HDF7qOAKc_sM
###

PUT http://localhost:3000/Update HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkVDSFUxM0BnbWFpbC5jb20iLCJpYXQiOjE3MjczNjI5NjksImV4cCI6MzUyNzM2Mjk2OX0.TPY5Sk8IoeN7tv3dxLcKUMWOGffWU44HDF7qOAKc_sM
Content-Type: application/json

{
    "NombreUsuario": " V1g1_IWNL",
    "Mail": "nacho.vigilante@gmail.com",
    "Contraseña":"hasheo",
    "admin": true
}
//Conversación
###
GET http://localhost:3000/GetFeedback/10 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkVDSFUxM0BnbWFpbC5jb20iLCJpYXQiOjE3MjczNjI5NjksImV4cCI6MzUyNzM2Mjk2OX0.TPY5Sk8IoeN7tv3dxLcKUMWOGffWU44HDF7qOAKc_sM
###
POST http://localhost:3000/CrearFeedback HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkVDSFUxM0BnbWFpbC5jb20iLCJpYXQiOjE3MjczNjI5NjksImV4cCI6MzUyNzM2Mjk2OX0.TPY5Sk8IoeN7tv3dxLcKUMWOGffWU44HDF7qOAKc_sM
Content-Type: application/json

{
  "Feedback": "godiiii",
  "Mail_Usuario": "ECHU13@gmail.com"
}

###
DELETE http://localhost:3000/EliminarConver/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkVDSFUxM0BnbWFpbC5jb20iLCJpYXQiOjE3MjczNjI5NjksImV4cCI6MzUyNzM2Mjk2OX0.TPY5Sk8IoeN7tv3dxLcKUMWOGffWU44HDF7qOAKc_sM
###

PUT  http://localhost:3000/43/UpdateFeed HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkVDSFUxM0BnbWFpbC5jb20iLCJpYXQiOjE3Mjc3MTY3NzksImV4cCI6MzUyNzcxNjc3OX0.tg5_IgQWQYs2GsPJQ2VJ28fE6EzL0FteYdmSPEzO6f0
Content-Type: application/json

{
  "Feedback":"Miaaaaameeeeeeeeeeeeeee"
}

###

PUT  http://localhost:3000/50/texto HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkVDSFUxM0BnbWFpbC5jb20iLCJpYXQiOjE3MjczNjI5NjksImV4cCI6MzUyNzM2Mjk2OX0.TPY5Sk8IoeN7tv3dxLcKUMWOGffWU44HDF7qOAKc_sM
Content-Type: application/json

{
  "translation":"Hola soy echu y me gusta mucho la materia"
  
}

###
GET  http://localhost:3000/43/getTexto HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkVDSFVAZ21haWwuY29tIiwiaWF0IjoxNzI5OTc1MDE4LCJleHAiOjM1Mjk5NzUwMTh9.K5U4VM6QT2o0j0OHrlqH48bvyNTwkhqxDOdFxWmH-d8
